apiVersion: v1
kind: Service
metadata:
  name: elearning-service
  namespace: elearning
spec:
  type: NodePort
  selector:
    app: elearning
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007